# Generated by Django 5.1.3 on 2024-12-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.UniqueConstraint(
                fields=("course", "subject", "teacher", "day_of_week", "hour"),
                name="unique_schedule",
            ),
        ),
    ]
