# Generated by Django 5.1.3 on 2024-12-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_schedule_unique_schedule"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="schedule",
            name="unique_schedule",
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="hour",
            new_name="start_time",
        ),
        migrations.AddField(
            model_name="schedule",
            name="end_time",
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.UniqueConstraint(
                fields=(
                    "course",
                    "subject",
                    "teacher",
                    "day_of_week",
                    "start_time",
                    "end_time",
                ),
                name="unique_schedule",
            ),
        ),
    ]
