# Generated by Django 5.1.3 on 2024-12-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_remove_schedule_unique_schedule_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                ],
                max_length=9,
            ),
        ),
    ]
